server:
  port: 8080

spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    #    org.springframework.web: trace
    org.springframework.web: info
    com:
      roncoo:
        eshop:
          cache: info