server:
  port: 8081

spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ehcahe?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappings/*Mapper.xml
  type-aliases-package: com.example.mvc.mapper


logging:
  level:
    root: info
    org.mybatis: debug
    java.sql: debug
    org.springframework.web: trace
    com:
      service: debug